---
# handlers file for post-install

- name: restart ntp service on ubuntu
  ansible.builtin.service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: restart chronyd service on centos
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_distribution == "CentOS"

