---
- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: install http
      ansible.builtin.yum:
        name: httpd
        state: present


    - name: start http service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes  

- name: DBserver
  hosts: dbservers
  become: yes
  tasks:
    - name: install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    
    - name: start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes  
