---
- name: provisioning server
  hosts: all 
  become: yes
  roles:
    - role: post-install
      vars:
        ntp0: 0.in.pool.ntp.org
        ntp1: 1.in.pool.ntp.org
        ntp2: 2.in.pool.ntp.org
        ntp3: 3.in.pool.ntp.org  



