---
- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: install http
      ansible.builtin.yum:
        name: httpd
        state: present


    - name: start http service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes  
   

    - name: Copy Index file
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        backup: yes
